export enum NodeType {
  FILE = 'FILE',
  MODULE = 'MODULE',
  CLASS = 'CLASS',
  FUNCTION = 'FUNCTION',
  INTERFACE = 'INTERFACE',
  TYPE = 'TYPE',
  VARIABLE = 'VARIABLE',
  IMPORT = 'IMPORT',
  EXPORT = 'EXPORT',
}

export enum EdgeType {
  IMPORTS = 'IMPORTS',
  EXPORTS = 'EXPORTS',
  EXTENDS = 'EXTENDS',
  IMPLEMENTS = 'IMPLEMENTS',
  COMPOSES = 'COMPOSES',
  DEPENDS_ON = 'DEPENDS_ON',
  REFERENCES = 'REFERENCES',
  CONTAINS = 'CONTAINS',
}
