export enum RetrievalScope {
  NODE = 'NODE',
  SYMBOL = 'SYMBOL',
  MODULE = 'MODULE',
  CLUSTER = 'CLUSTER',
  SNAPSHOT = 'SNAPSHOT',
  SUBGRAPH = 'SUBGRAPH',
}

export enum RetrievalStrategy {
  DEPENDENCY_NEIGHBORHOOD = 'DEPENDENCY_NEIGHBORHOOD',
  SYMBOL_NEIGHBORHOOD = 'SYMBOL_NEIGHBORHOOD',
  BLAST_RADIUS = 'BLAST_RADIUS',
  ARCHITECTURAL_SLICE = 'ARCHITECTURAL_SLICE',
  SEMANTIC_CLUSTER = 'SEMANTIC_CLUSTER',
  DEPTH_LIMITED = 'DEPTH_LIMITED',
  METRIC_WEIGHTED = 'METRIC_WEIGHTED',
}

export enum RetrievalOrdering {
  DEPTH_ASC = 'DEPTH_ASC',
  DEPTH_DESC = 'DEPTH_DESC',
  RISK_DESC = 'RISK_DESC',
  CENTRALITY_DESC = 'CENTRALITY_DESC',
  STABILITY_DESC = 'STABILITY_DESC',
  SEMANTIC_IMPORTANCE_DESC = 'SEMANTIC_IMPORTANCE_DESC',
  DETERMINISTIC = 'DETERMINISTIC',
}
