export enum SemanticType {
  API_LAYER = 'API_LAYER',
  SERVICE_LAYER = 'SERVICE_LAYER',
  DATA_LAYER = 'DATA_LAYER',
  DOMAIN_LAYER = 'DOMAIN_LAYER',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  UI_LAYER = 'UI_LAYER',
  SHARED_UTILITY = 'SHARED_UTILITY',
  CONFIGURATION = 'CONFIGURATION',
  TESTING = 'TESTING',
  BUILD_SYSTEM = 'BUILD_SYSTEM',
  SECURITY = 'SECURITY',
  OBSERVABILITY = 'OBSERVABILITY',
  UNKNOWN = 'UNKNOWN',
}

export enum CouplingType {
  TIGHT_COUPLING = 'TIGHT_COUPLING',
  MODERATE_COUPLING = 'MODERATE_COUPLING',
  LOOSE_COUPLING = 'LOOSE_COUPLING',
  CYCLIC_COUPLING = 'CYCLIC_COUPLING',
  SHARED_STATE_COUPLING = 'SHARED_STATE_COUPLING',
  INFRASTRUCTURE_COUPLING = 'INFRASTRUCTURE_COUPLING',
}

export enum RuleStrength {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}
