export { projects } from './projects.ts';
export { snapshots } from './snapshots.ts';
export { nodes } from './nodes.ts';
export { edges } from './edges.ts';
export { risks } from './risks.ts';
export { insights } from './insights.ts';
export { eventLogs } from './event-log.ts';
export { jobQueue } from './job-queue.ts';
export { compressedFileContexts } from './compressed-file-contexts.ts';
export { compressedModuleContexts } from './compressed-module-contexts.ts';
export { compressedRepositoryContexts } from './compressed-repository-contexts.ts';
export { compressionMetrics } from './compression-metrics.ts';

export type { Project, NewProject } from './projects.ts';
export type { Snapshot, NewSnapshot } from './snapshots.ts';
export type { Node, NewNode } from './nodes.ts';
export type { Edge, NewEdge } from './edges.ts';
export type { Risk, NewRisk } from './risks.ts';
export type { Insight, NewInsight } from './insights.ts';
export type { EventLog, NewEventLog } from './event-log.ts';
export type { JobQueue, NewJobQueue } from './job-queue.ts';
export type { CompressedFileContextRow, NewCompressedFileContextRow } from './compressed-file-contexts.ts';
export type { CompressedModuleContextRow, NewCompressedModuleContextRow } from './compressed-module-contexts.ts';
export type { CompressedRepositoryContextRow, NewCompressedRepositoryContextRow } from './compressed-repository-contexts.ts';
export type { CompressionMetricsRow, NewCompressionMetricsRow } from './compression-metrics.ts';
export { snapshotLineage } from './snapshot-lineage.ts';
export { snapshotDiffs } from './snapshot-diffs.ts';
export { reuseArtifacts } from './reuse-artifacts.ts';
export { invalidationRegions } from './invalidation-regions.ts';
export { incrementalMetrics } from './incremental-metrics.ts';
export type { SnapshotLineage, NewSnapshotLineage } from './snapshot-lineage.ts';
export type { SnapshotDiffRow, NewSnapshotDiffRow } from './snapshot-diffs.ts';
export type { ReuseArtifact, NewReuseArtifact } from './reuse-artifacts.ts';
export type { InvalidationRegion, NewInvalidationRegion } from './invalidation-regions.ts';
export type { IncrementalMetricsRow, NewIncrementalMetricsRow } from './incremental-metrics.ts';

export { semanticClassifications } from './semantic-metadata.ts';
export type { SemanticClassificationRow, NewSemanticClassificationRow } from './semantic-metadata.ts';
export { domainClusters } from './domain-clusters.ts';
export type { DomainClusterRow, NewDomainClusterRow } from './domain-clusters.ts';
export { couplingEdges } from './coupling-analysis.ts';
export type { CouplingEdgeRow, NewCouplingEdgeRow } from './coupling-analysis.ts';
export { graphMetrics } from './graph-metrics.ts';
export type { GraphMetricsRow, NewGraphMetricsRow } from './graph-metrics.ts';
export { validationResults, snapshotIntegrity } from './validation-results.ts';
export type { ValidationResultRow, NewValidationResultRow, SnapshotIntegrityRow, NewSnapshotIntegrityRow } from './validation-results.ts';

export { promptRegistry } from './prompt-registry.ts';
export type { PromptRegistryRow, NewPromptRegistryRow } from './prompt-registry.ts';

export { executionHistory } from './execution-history.ts';
export type { ExecutionHistoryRow, NewExecutionHistoryRow } from './execution-history.ts';

export { graphInsights } from './graph-insights.ts';
export type { GraphInsight, NewGraphInsight } from './graph-insights.ts';
export { ruleExecutions } from './rule-executions.ts';
export type { RuleExecution, NewRuleExecution } from './rule-executions.ts';
export { evidenceLinks } from './evidence-links.ts';
export type { EvidenceLink, NewEvidenceLink } from './evidence-links.ts';
export { architectureFindings } from './architecture-findings.ts';
export type { ArchitectureFinding, NewArchitectureFinding } from './architecture-findings.ts';

export { memorySnapshots } from './memory/memory-snapshots.ts';
export type { MemorySnapshotRow, NewMemorySnapshotRow } from './memory/memory-snapshots.ts';
export { memoryEntries } from './memory/memory-entries.ts';
export type { MemoryEntryRow, NewMemoryEntryRow } from './memory/memory-entries.ts';
export { memoryRelations } from './memory/memory-relations.ts';
export type { MemoryRelationRow, NewMemoryRelationRow } from './memory/memory-relations.ts';
export { reasoningChains } from './memory/reasoning-chains.ts';
export type { ReasoningChainRow, NewReasoningChainRow } from './memory/reasoning-chains.ts';
export { retrievalHistory } from './memory/retrieval-history.ts';
export type { RetrievalHistoryRow, NewRetrievalHistoryRow } from './memory/retrieval-history.ts';
export { contextEnvelopes } from './memory/context-envelopes.ts';
export type { ContextEnvelopeRow, NewContextEnvelopeRow } from './memory/context-envelopes.ts';

export { recommendations } from './recommendations.ts';
export type { Recommendation, NewRecommendation } from './recommendations.ts';
export { architecturePatterns } from './architecture-patterns.ts';
export type { ArchitecturePattern, NewArchitecturePattern } from './architecture-patterns.ts';
export { riskCorrelations } from './risk-correlations.ts';
export type { RiskCorrelation, NewRiskCorrelation } from './risk-correlations.ts';
export { cognitionSnapshots } from './cognition-snapshots.ts';
export type { CognitionSnapshot, NewCognitionSnapshot } from './cognition-snapshots.ts';
export { narratives } from './narratives.ts';
export type { Narrative, NewNarrative } from './narratives.ts';
export { reports } from './reports.ts';
export type { Report, NewReport } from './reports.ts';
export { architectureDiffs } from './architecture-diffs.ts';
export type { ArchitectureDiff, NewArchitectureDiff } from './architecture-diffs.ts';
export { cognitionTimeseries } from './cognition-timeseries.ts';
export type { CognitionTimeseries, NewCognitionTimeseries } from './cognition-timeseries.ts';
export { architectureTrends } from './architecture-trends.ts';
export type { ArchitectureTrend, NewArchitectureTrend } from './architecture-trends.ts';
export { queryHistory } from './query-history.ts';
export type { QueryHistory, NewQueryHistory } from './query-history.ts';
export { searchIndexes } from './search-indexes.ts';
export type { SearchIndexRow, NewSearchIndexRow } from './search-indexes.ts';
export { cognitionIndexes } from './cognition-indexes.ts';
export type { CognitionIndexRow, NewCognitionIndexRow } from './cognition-indexes.ts';
export { knowledgeGraph } from './knowledge-graph.ts';
export type { KnowledgeGraphRow, NewKnowledgeGraphRow } from './knowledge-graph.ts';
export { knowledgeRelations } from './knowledge-relations.ts';
export type { KnowledgeRelationRow, NewKnowledgeRelationRow } from './knowledge-relations.ts';

export { analysisSessions, sessionTimelines, reasoningSnapshots, investigationMetadata, sessionReplayLinks, sessionAIInteractions } from './sessions.ts';
export type { AnalysisSession, NewAnalysisSession, SessionTimeline, NewSessionTimeline, ReasoningSnapshot, NewReasoningSnapshot, InvestigationMetadata, NewInvestigationMetadata, SessionReplayLink, NewSessionReplayLink, SessionAIInteraction, NewSessionAIInteraction } from './sessions.ts';

export { explorationSessions, explorationQueries, traversalHistory, explorationBookmarksDb, traversalReplayDb, pathAnalysisResults, neighborhoodCache } from './exploration.ts';
export type { ExplorationSessionRow, NewExplorationSessionRow, ExplorationQueryRow, NewExplorationQueryRow, TraversalHistoryRow, NewTraversalHistoryRow, ExplorationBookmarkRow, NewExplorationBookmarkRow, TraversalReplayRow, NewTraversalReplayRow, PathAnalysisResultRow, NewPathAnalysisResultRow, NeighborhoodCacheRow, NewNeighborhoodCacheRow } from './exploration.ts';
